/**
 * True Path — result store.
 *
 * The finished report gets a persistent id so it can be revisited or emailed (Brief 12).
 * Answers stay in sessionStorage; only the final report is persisted server-side.
 *
 * Uses the Upstash / Vercel KV REST API over `fetch`, so no extra dependency is introduced.
 * The store is OPTIONAL for reading: with no credentials configured the read paths return
 * null/false and the report page degrades to its self-contained payload link rather than
 * breaking. It is REQUIRED for writes a visitor would otherwise be misled about — see
 * StoreNotConfiguredError.
 */

const KEY_PREFIX = 'tfp:truepath:result:';
const EMAIL_PREFIX = 'tfp:truepath:emailed:';
const LEAD_PREFIX = 'tfp:truepath:lead:';

/** 90 days, in seconds. */
const RESULT_TTL_SECONDS = 60 * 60 * 24 * 90;

/** resultIds are generated by the client; only allow the shape we expect. */
const RESULT_ID_PATTERN = /^tp_[A-Za-z0-9_-]{4,64}$/;

type RestConfig = { url: string; token: string };

/**
 * Which vars configure the store is pure logic, so it lives in `true-path/lib/store-config.js`
 * where it is type-checked and unit-tested. This wrapper only supplies the real environment.
 */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const StoreConfig = require('../true-path/lib/store-config.js') as {
  resolveRestConfig(env: Record<string, string | undefined>): RestConfig | null;
};

function getRestConfig(): RestConfig | null {
  return StoreConfig.resolveRestConfig(process.env);
}

/**
 * Thrown when an operation that genuinely needs the store runs with no credentials configured.
 *
 * Callers map this to an explicit 503. It exists so a missing store can never be mistaken for
 * a successful write, and never for `false` — which for claimEmailSend means "duplicate".
 */
export class StoreNotConfiguredError extends Error {
  code = 'storage_not_configured';

  constructor(message = 'True Path store is not configured') {
    super(message);
    this.name = 'StoreNotConfiguredError';
  }
}

/** True when a KV store is configured. Callers use this to report honest status. */
export function isStoreConfigured(): boolean {
  return getRestConfig() !== null;
}

export function isValidResultId(value: unknown): boolean {
  return typeof value === 'string' && RESULT_ID_PATTERN.test(value);
}

async function command(args: (string | number)[]): Promise<unknown> {
  const config = getRestConfig();
  if (!config) return null;

  const response = await fetch(config.url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${config.token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(args),
  });

  if (!response.ok) {
    throw new Error(`KV request failed with status ${response.status}`);
  }

  const payload = await response.json();
  return (payload as { result?: unknown }).result ?? null;
}

/** Persist a finished Section 13 record. Returns false when no store is configured. */
export async function saveResult(record: Record<string, unknown>): Promise<boolean> {
  const resultId = record.resultId;
  if (!isValidResultId(resultId)) throw new Error('Invalid resultId');

  const result = await command([
    'SET',
    KEY_PREFIX + String(resultId),
    JSON.stringify(record),
    'EX',
    String(RESULT_TTL_SECONDS),
  ]);

  return result !== null;
}

/**
 * Persist a record only if that resultId is not stored yet.
 *
 * The report page re-posts its record on every load, including a reload of an
 * `?id=`/`?r=` link. Writing unconditionally would overwrite the stored record and destroy the
 * `lead` block that the visitor already submitted, so the first write wins.
 */
export async function saveResultOnce(record: Record<string, unknown>): Promise<boolean> {
  const resultId = record.resultId;
  if (!isValidResultId(resultId)) throw new Error('Invalid resultId');

  const result = await command([
    'SET',
    KEY_PREFIX + String(resultId),
    JSON.stringify(record),
    'EX',
    String(RESULT_TTL_SECONDS),
    'NX'
  ]);

  // null means the key already existed, which is a success for this helper.
  if (result !== null) return true;

  const existing = await command(['EXISTS', KEY_PREFIX + String(resultId)]);
  return Number(existing) > 0;
}

/** Load a persisted record, or null when it is missing/unavailable. */
export async function loadResult(resultId: unknown): Promise<Record<string, unknown> | null> {
  if (!isValidResultId(resultId)) return null;

  const raw = await command(['GET', KEY_PREFIX + String(resultId)]);
  if (typeof raw !== 'string' || !raw) return null;

  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

/** Attach the captured lead to an existing record (Brief 13 `lead` block). */
export async function saveLead(
  resultId: unknown,
  lead: Record<string, unknown>
): Promise<boolean> {
  if (!isValidResultId(resultId)) return false;

  const record = await loadResult(resultId);
  if (!record) {
    // Keep the lead even if the result has expired, so no enquiry is ever lost.
    await command([
      'SET',
      LEAD_PREFIX + String(resultId),
      JSON.stringify(lead),
      'EX',
      String(RESULT_TTL_SECONDS),
    ]);
    return false;
  }

  record.lead = { ...(record.lead as object), ...lead };
  await saveResult(record);
  return true;
}

/**
 * Idempotency guard for report email delivery.
 *
 * Returns true only for the FIRST caller for a given resultId, so a retried or double-clicked
 * submission cannot send the same report twice (Brief 17), and false for a duplicate. Throws
 * StoreNotConfiguredError when no store is configured: without one we cannot deduplicate, and
 * sending on every retry is worse than refusing. `false` therefore means duplicate and ONLY
 * duplicate — never "we could not check".
 */
export async function claimEmailSend(resultId: unknown): Promise<boolean> {
  if (!isValidResultId(resultId)) return true;
  if (!isStoreConfigured()) {
    throw new StoreNotConfiguredError('Cannot claim an email send without a configured store');
  }

  const result = await command([
    'SET',
    EMAIL_PREFIX + String(resultId),
    new Date().toISOString(),
    'EX',
    String(RESULT_TTL_SECONDS),
    'NX',
  ]);

  // "OK" means the key was newly set; null means it already existed.
  return result !== null;
}

/**
 * Drop an email-send claim after a delivery failure, so the visitor's retry can still succeed.
 * Without this a transient Resend error would permanently block that report from being emailed.
 */
export async function releaseEmailSend(resultId: unknown): Promise<void> {
  if (!isValidResultId(resultId)) return;
  await command(['DEL', EMAIL_PREFIX + String(resultId)]);
}
